### ISSUE TITLE
Passwords included in log output

### ISSUE THREAD

**Issue by harrybiddle** [mara/mara-pipelines#65]
When using the `ExecuteSQL` command with a PostgreSQL database, passwords are leaked to the logs:

<img width="678" alt="image" src="https://user-images.githubusercontent.com/5887227/147587325-b3f1bbb7-9e5f-4141-b015-c832a4af5d71.png">

It would be better to pass sensitive values using Popen's `env` option.

~(If you also passed in the query as the process' stdin, you wouldn't have to worry about quoting with `shlex.quote`):~

**Comment by jankatins** [comment]
This doesn't quite work as we eecute a whole pipe and so the env variable can be on both sides (and with different passwords).

There is `mara_pipelines.config.password_masks()` which will replace everything returned by this function before it is shown/persisted: https://github.com/mara/mara-pipelines/blob/master/mara_pipelines/logging/logger.py#L29-L32

**Comment by harrybiddle** [comment]
Great, thanks! This is working for me.
