### ISSUE TITLE
Make PyPI package graphviz optional

### ISSUE THREAD

**Issue by leo-schick** [mara/mara-pipelines#70]
Currently the PyPI package **graphviz** is required. I tested out running a mara instance on [Google App Engine](https://cloud.google.com/appengine) which worked fine except that you are not able to install additional linux packages (except you spin up a docker image which costs extra).

Would be interesting to investigate making graphviz optional by using the JS engine [d3-graphviz](https://github.com/magjac/d3-graphviz) when python package `graphviz` is not installed.

In addition, when running mara_pipelines headless there isn't a reason for graphviz and therefore IMHO this package should be defined as an extra requirement.

**Comment by jankatins** [comment]
Any bad perf for big graphs (e.g. when memory starved or similar?)? If not, I would say go for it :-)

**Comment by leo-schick** [comment]
I came now up with this soltion solution:

Mara Pipeline will by default use the graphviz shell tools. In case they are not found (exception `graphviz.backend.ExecutableNotFound` is thrown) we use a fallback to client-side rendering with d3-graphviz.
If that fails as well, you will still see the python exception thrown by graphviz.

For client-side rendering with d3-graphviz one has to add the following javascript libraries to the mara app:

``` python
@monkey_patch.wrap(mara_app.layout.js_files)
def js_files(original_function, response):
    files = original_function(response)
    files.append('https://d3js.org/d3.v7.min.js')
    files.append('https://unpkg.com/@hpcc-js/wasm@1.14.1/dist/index.min.js')
    files.append('https://unpkg.com/d3-graphviz@4.1.1/build/d3-graphviz.js')
    return files
```
