### ISSUE TITLE
add HTTP Request command

### ISSUE THREAD

**Issue by leo-schick** [mara/mara-pipelines#78]
I plan to add a new `HttpRequestCommand` which shall run a HTTP/HTTPS command via [curl](https://everything.curl.dev/).

It should keep the output clean (using option `-s`) and fail when the request returns an error code (option `-f`).

### Things to implement
* support different request types (arg `-X`), using `GET` requests by default
* support passing headers (option `-H`)
* implement a command which generates the shell command string with an option to pass data from stdin (option `--data-binary @-`)

### Possible use cases

- calling an API function with an access token
- running a serverless cloud function (AWS Lambda / Google Cloud Function / Azure Function command) via HTTP request

### How to implement

- add a new function `http_request_command(...)` in `mara_pipelines.shell`
- add a new command `HttpRequestCommand` in `mara_pipelines.commands.http`

**Comment by leo-schick** [comment]
@jankatins any comments about the design?

**Comment by jankatins** [comment]
I always did that directly via curl or python, so sounds fine.

I've not yet a clue on the stdin thingy, how would you use that?

**Comment by leo-schick** [comment]
I build a cloud function which validates a XML file against a schema and converts it to json. To process this logic through files in a directory the shell command would look roughly like this:
``` python
shell_command = f"{mara_storage.shell.read_file_command(...) \\\n" \
                f"  | {mara_pipelines.shell.http_request_command(...)} \\\n" \
                f"  | {mara_storage.shell.write_file_command(..)"
```
